### ISSUE TITLE
A lot of "Fetch" errors and more...

### ISSUE THREAD

**Issue by geeknessfr** [Dev-CasperTheGhost/snaily-cad#1]
Hi,

We tried your CAD for our server, but i get some bugs...

First when trying to start with "npm start" i get this error :
```
CHECKING CAD VERSION.
Running on 20800
(node:4341) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at https://dev-caspertheghost.github.io/portofolio/api/version.html reason: Unexpected token < in JSON at position 0
    at /home/fivem/snailycad/node_modules/node-fetch/lib/index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async main (/home/fivem/snailycad/server.js:330:27)
(node:4341) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4341) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

So, I modified the code in server.js and removed the version check...

The CAD starts, and we can connect and create an account... but when trying to make different sort of actions I get this error in console : 
```
(node:4806) UnhandledPromiseRejectionWarning: FetchError: request to http://95.179.141.103:3000/ failed, reason: connect ETIMEDOUT 95.179.141.103:3000
    at ClientRequest.<anonymous> (/home/fivem/snailycad/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:209:13)
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:209:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:4806) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
Error: ER_NO_SUCH_TABLE: Table 'snaily-cad.cads' doesn't exist
    at Query.Sequence._packetToError (/home/fivem/snailycad/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/fivem/snailycad/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/fivem/snailycad/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/fivem/snailycad/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/fivem/snailycad/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/fivem/snailycad/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/fivem/snailycad/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/fivem/snailycad/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:209:13)
    at addChunk (_stream_readable.js:305:12)
    --------------------
    at Protocol._enqueue (/home/fivem/snailycad/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/fivem/snailycad/node_modules/mysql/lib/Connection.js:198:25)
    at Query.<anonymous> (/home/fivem/snailycad/routes/login-reg.js:274:28)
    at Query.<anonymous> (/home/fivem/snailycad/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/fivem/snailycad/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/home/fivem/snailycad/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query._handleFinalResultPacket (/home/fivem/snailycad/node_modules/mysql/lib/protocol/sequences/Query.js:149:8)
    at Query.EofPacket (/home/fivem/snailycad/node_modules/mysql/lib/protocol/sequences/Query.js:133:8)
    at Protocol._parsePacket (/home/fivem/snailycad/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/fivem/snailycad/node_modules/mysql/lib/protocol/Parser.js:433:10) {
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlMessage: "Table 'snaily-cad.cads' doesn't exist",
  sqlState: '42S02',
  index: 0,
  sql: "SELECT cadID FROM `cads` WHERE cadID = 'undefined'"
}
```
And a lot of others errors...

Finally we just can't use your CAD... :(
And where are you creating a Police Dept. .. ? The CAD said we don't have one, but we can't figure where to create one...

Please help ^^

**Comment by casperiv0** [comment]
Hello @geeknessfr,

I've looked into this and I found the bug, it should be fix with the next update!

To get a department you have to go to the admin panel => click the values button => Departments => add department. 

If you have any more questions feel free to ask!

**Comment by geeknessfr** [comment]
Thanks a lot for your answer ! ;)

We'll be waiting for your update !

**Comment by casperiv0** [comment]
Should be updated now, Just run `git pull origin master` to pull the newest version.

**Comment by geeknessfr** [comment]
Thanks !

Just tried the update, it's a lot better !

I still get this error when trying to go to Police Dashboard : 
```
(node:5485) UnhandledPromiseRejectionWarning: FetchError: request to http://95.179.141.103:3000/ failed, reason: connect ETIMEDOUT 95.179.141.103:3000
    at ClientRequest.<anonymous> (/home/fivem/snailycad/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:209:13)
    at Socket.socketErrorListener (_http_client.js:406:9)
    at Socket.emit (events.js:209:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:5485) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5485) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

And at the top there is this text : Police Department - **AOP: Change Me**

**Comment by casperiv0** [comment]
Ah yeah, that was my penal code API, I shut it down because it's now open source, there's a .json file in the directory with the penal codes now, I think I just forgot to remove some of the code lol

Sorry for the inconvenience

**Comment by geeknessfr** [comment]
No problem, i betatest your project ^^ ;)

Your reactivity is awesome ! ^^

**Comment by casperiv0** [comment]
Thanks!

It should be updated now. :)

**Comment by geeknessfr** [comment]
You are belgian ? Speaking "French" ? because i'm french ^^ If you have a Discord account try to add me : Geekness#7280
